import React, { createContext, useState, useContext } from 'react';

export type Language = 'tr' | 'en' | 'de' | 'fr' | 'ru' | 'ar';

export interface Translations {
  title: string;
  subtitle: string;
  diagnosticsTitle: string;
  diagnosticsSub: string;
  diagnosticsCheck: string;
  runDiagnostics: string;
  card1Title: string;
  card1Desc: string;
  card2Title: string;
  card2Desc: string;
  card3Title: string;
  card3Desc: string;
  settingsTitle: string;
  settingsDesc: string;
  batterySystem: string;
  pulse10v: string;
  pulse33v: string;
  regulator33to5: string;
  boostConverter: string;
  transmitterSystem: string;
  receiverSystem: string;
  gpsConnection: string;
  aiEngine: string;
  storageSystem: string;
  statusReady: string;
  statusWarning: string;
  statusFault: string;
  startScan: string;
  stopScan: string;
  pauseScan: string;
  scanProgress: string;
  signalQuality: string;
  scanStatus: string;
  aiAlerts: string;
  radargram: string;
  liveSignalStream: string;
  signalStrength: string;
  penetrationDepth: string;
  targetMarkers: string;
  reflectionVisual: string;
  scanCoverageMap: string;
  transmitterPanel: string;
  pulseWaveform: string;
  peakVoltage: string;
  pulseWidth: string;
  pulseFreq: string;
  repRate: string;
  amplitude: string;
  fftSpectrum: string;
  powerPanel: string;
  batteryPercentage: string;
  batteryVoltage: string;
  operatingTime: string;
  currentConsumption: string;
  temperature: string;
  receiverPanel: string;
  reflectionDelay: string;
  reflectionStrength: string;
  attenuation: string;
  materialConfidence: string;
  aiDetectionTitle: string;
  objectType: string;
  confidenceScore: string;
  estimatedDepth: string;
  estimatedDim: string;
  detectionTime: string;
  whyClassified: string;
  similarityScore: string;
  dielectricEstimate: string;
  frequencyResponse: string;
  threeDSubsurface: string;
  soilLayers: string;
  undergroundObjects: string;
  voids: string;
  utilities: string;
  geologicalStructures: string;
  rotate: string;
  pan: string;
  zoom: string;
  layerToggle: string;
  transparency: string;
  sectionCut: string;
  volumeRender: string;
  smartAlerts: string;
  materialAnalysisTitle: string;
  materialPrediction: string;
  frequencySignature: string;
  reflectionSignature: string;
  similarObjects: string;
  freqCurves: string;
  reflectionGraphs: string;
  similarityCharts: string;
  aiExplanation: string;
  logsTitle: string;
  gpsLoc: string;
  operator: string;
  duration: string;
  results: string;
  listView: string;
  timelineView: string;
  mapView: string;
  exportPdf: string;
  exportCsv: string;
  exportPng: string;
  aiCopilotTitle: string;
  settingsFreq: string;
  settingsPulse: string;
  settingsGain: string;
  settingsNoise: string;
  settingsAntenna: string;
  settingsRes: string;
  settingsLang: string;
  settingsTheme: string;
  settingsGps: string;
  settingsStorage: string;
  targetDetected: string;
  gold: string;
  silver: string;
  copper: string;
  iron: string;
  aluminum: string;
  pipe: string;
  cable: string;
  concrete: string;
  water: string;
  rock: string;
  plastic: string;
  void: string;
  tunnel: string;
  buriedObj: string;
  unknownObj: string;
  metal: string;
  steel: string;
  soil: string;
  emptyVoid: string;
}

const translationsMap: Record<Language, Translations> = {
  tr: {
    title: "AntiGravity AI GPR Suite",
    subtitle: "Endüstriyel Yapay Zeka Destekli Yeraltı Radarı",
    diagnosticsTitle: "Donanım Teşhis Sistemi",
    diagnosticsSub: "Sistem başlatılıyor ve donanım testleri gerçekleştiriliyor...",
    diagnosticsCheck: "Kontrol Ediliyor...",
    runDiagnostics: "Testi Yeniden Başlat",
    card1Title: "CANLI GPR TARAMASI",
    card1Desc: "Gerçek zamanlı yeraltı tarama ve yapay zeka analiz modu",
    card2Title: "MADDE ANALİZİ",
    card2Desc: "Frekans yanıtı ile malzeme türü tahmini ve detaylı spektrum",
    card3Title: "KAYITLAR VE KONUMLAR",
    card3Desc: "Geçmiş tarama verileri, GPS rotaları ve rapor dışa aktarma",
    settingsTitle: "AYARLAR",
    settingsDesc: "Donanım parametreleri, sinyal filtreleme ve genel tercihler",
    batterySystem: "Pil Sistemi",
    pulse10v: "Puls 10V Jeneratörü",
    pulse33v: "Puls 3.3V Jeneratörü",
    regulator33to5: "3.3V → 5V Regülatörü",
    boostConverter: "Boost Dönüştürücü",
    transmitterSystem: "Verici Sistem",
    receiverSystem: "Alıcı Sistem",
    gpsConnection: "GPS Bağlantısı",
    aiEngine: "Yapay Zeka Analiz Motoru",
    storageSystem: "Hafıza ve Kayıt Sistemi",
    statusReady: "Hazır",
    statusWarning: "Uyarı",
    statusFault: "Hata",
    startScan: "Taramayı Başlat",
    stopScan: "Taramayı Durdur",
    pauseScan: "Duraklat",
    scanProgress: "Tarama İlerlemesi",
    signalQuality: "Sinyal Kalitesi",
    scanStatus: "Yer Tarama Durumu",
    aiAlerts: "YZ Tespit Uyarıları",
    radargram: "Gerçek Zamanlı Radargram",
    liveSignalStream: "Canlı Sinyal Akışı",
    signalStrength: "Sinyal Gücü",
    penetrationDepth: "Nüfuz Etme Derinliği",
    targetMarkers: "Hedef İşaretçiler",
    reflectionVisual: "Yansıma Görselleştirme",
    scanCoverageMap: "Tarama Kapsama Haritası",
    transmitterPanel: "Verici İzleme Paneli",
    pulseWaveform: "Puls Dalga Formu",
    peakVoltage: "Tepe Gerilimi",
    pulseWidth: "Puls Genişliği",
    pulseFreq: "Puls Frekansı",
    repRate: "Tekrarlama Oranı",
    amplitude: "Genlik",
    fftSpectrum: "FFT Spektrum Analizi",
    powerPanel: "Güç İzleme Paneli",
    batteryPercentage: "Pil Yüzdesi",
    batteryVoltage: "Pil Gerilimi",
    operatingTime: "Kalan Çalışma Süresi",
    currentConsumption: "Akım Tüketimi",
    temperature: "Sıcaklık",
    receiverPanel: "Alıcı Analiz Paneli",
    reflectionDelay: "Yansıma Gecikmesi",
    reflectionStrength: "Yansıma Gücü",
    attenuation: "Sinyal Zayıflaması",
    materialConfidence: "Malzeme Güven Skoru",
    aiDetectionTitle: "Yapay Zeka Nesne Tespiti",
    objectType: "Nesne Türü",
    confidenceScore: "Güven Skoru",
    estimatedDepth: "Tahmini Derinlik",
    estimatedDim: "Tahmini Boyutlar",
    detectionTime: "Tespit Zamanı",
    whyClassified: "Sınıflandırma Nedeni",
    similarityScore: "Benzerlik Skoru",
    dielectricEstimate: "Dielektrik Tahmini",
    frequencyResponse: "Frekans Yanıtı",
    threeDSubsurface: "3D Yeraltı Görselleştirme",
    soilLayers: "Toprak Katmanları",
    undergroundObjects: "Yeraltı Nesneleri",
    voids: "Boşluklar",
    utilities: "Altyapı Hatları",
    geologicalStructures: "Jeolojik Yapılar",
    rotate: "Döndür",
    pan: "Kaydır",
    zoom: "Yakınlaş",
    layerToggle: "Katman Aç/Kapa",
    transparency: "Şeffaflık Kontrolü",
    sectionCut: "Kesit Al",
    volumeRender: "Hacimsel Render",
    smartAlerts: "Akıllı Uyarı Sistemi",
    materialAnalysisTitle: "Madde Analizi Modu",
    materialPrediction: "Malzeme Tahmini",
    frequencySignature: "Frekans İmzası",
    reflectionSignature: "Yansıma İmzası",
    similarObjects: "Benzer Nesneler",
    freqCurves: "Frekans Yanıt Eğrileri",
    reflectionGraphs: "Yansıma Şiddet Grafikleri",
    similarityCharts: "Malzeme Benzerlik Tablosu",
    aiExplanation: "Yapay Zeka Analiz Açıklaması",
    logsTitle: "Kayıtlar ve Konumlar",
    gpsLoc: "GPS Konumu",
    operator: "Operatör",
    duration: "Tarama Süresi",
    results: "Tespit Sonuçları",
    listView: "Liste Görünümü",
    timelineView: "Zaman Çizelgesi",
    mapView: "Harita Görünümü",
    exportPdf: "PDF Raporu Dışa Aktar",
    exportCsv: "CSV Olarak Kaydet",
    exportPng: "PNG Grafik Dışa Aktar",
    aiCopilotTitle: "Yapay Zeka Yardımcı Pilot (AI Copilot)",
    settingsFreq: "Frekans Yapılandırması",
    settingsPulse: "Puls Yapılandırması",
    settingsGain: "Kazanç Kontrolü (Gain)",
    settingsNoise: "Gürültü Filtreleme",
    settingsAntenna: "Anten Parametreleri",
    settingsRes: "Tarama Çözünürlüğü",
    settingsLang: "Dil Seçimi",
    settingsTheme: "Tema Seçimi",
    settingsGps: "GPS Ayarları",
    settingsStorage: "Veri Depolama Ayarları",
    targetDetected: "Hedef Tespit Edildi!",
    gold: "Altın",
    silver: "Gümüş",
    copper: "Bakır",
    iron: "Demir",
    aluminum: "Alüminyum",
    pipe: "Boru / Tesisat",
    cable: "Kablo / Altyapı",
    concrete: "Beton Kütle",
    water: "Su / Islak Toprak",
    rock: "Kayaç",
    plastic: "Plastik Nesne",
    void: "Boşluk / Kavite",
    tunnel: "Tünel / Geçit",
    buriedObj: "Gömülü Nesne",
    unknownObj: "Bilinmeyen Nesne",
    metal: "Metal Nesne",
    steel: "Çelik Kiriş",
    soil: "Toprak Katmanı",
    emptyVoid: "Hava Boşluğu"
  },
  en: {
    title: "AntiGravity AI GPR Suite",
    subtitle: "Industrial AI-Powered Subsurface Radar",
    diagnosticsTitle: "Hardware Diagnostics System",
    diagnosticsSub: "Initializing system and executing hardware tests...",
    diagnosticsCheck: "Checking...",
    runDiagnostics: "Rerun Self-Test",
    card1Title: "LIVE GPR SCAN",
    card1Desc: "Real-time underground scanning and AI analysis mode",
    card2Title: "MATERIAL ANALYSIS",
    card2Desc: "Material type prediction via frequency response and spectrum",
    card3Title: "LOGS AND LOCATIONS",
    card3Desc: "Past scanning data, GPS routes, and report exporting",
    settingsTitle: "SETTINGS",
    settingsDesc: "Hardware parameters, signal filtering, and preferences",
    batterySystem: "Battery System",
    pulse10v: "Pulse 10V Generator",
    pulse33v: "Pulse 3.3V Generator",
    regulator33to5: "3.3V → 5V Regulator",
    boostConverter: "Boost Converter",
    transmitterSystem: "Transmitter System",
    receiverSystem: "Receiver System",
    gpsConnection: "GPS Connection",
    aiEngine: "AI Analysis Engine",
    storageSystem: "Storage & Logging System",
    statusReady: "Ready",
    statusWarning: "Warning",
    statusFault: "Fault",
    startScan: "Start Scan",
    stopScan: "Stop Scan",
    pauseScan: "Pause Scan",
    scanProgress: "Scan Progress",
    signalQuality: "Signal Quality",
    scanStatus: "Ground Scan Status",
    aiAlerts: "AI Detection Alerts",
    radargram: "Real-time Radargram",
    liveSignalStream: "Live Signal Stream",
    signalStrength: "Signal Strength",
    penetrationDepth: "Penetration Depth",
    targetMarkers: "Target Markers",
    reflectionVisual: "Reflection Visualization",
    scanCoverageMap: "Scan Coverage Map",
    transmitterPanel: "Transmitter Monitoring Panel",
    pulseWaveform: "Pulse Waveform",
    peakVoltage: "Peak Voltage",
    pulseWidth: "Pulse Width",
    pulseFreq: "Pulse Frequency",
    repRate: "Repetition Rate",
    amplitude: "Amplitude",
    fftSpectrum: "FFT Spectrum Analysis",
    powerPanel: "Power Monitoring Panel",
    batteryPercentage: "Battery Percentage",
    batteryVoltage: "Battery Voltage",
    operatingTime: "Est. Operating Time",
    currentConsumption: "Current Consumption",
    temperature: "Temperature",
    receiverPanel: "Receiver Analysis Panel",
    reflectionDelay: "Reflection Delay",
    reflectionStrength: "Reflection Strength",
    attenuation: "Signal Attenuation",
    materialConfidence: "Material Confidence Score",
    aiDetectionTitle: "AI Object Detection",
    objectType: "Object Type",
    confidenceScore: "Confidence Score",
    estimatedDepth: "Est. Depth",
    estimatedDim: "Est. Dimensions",
    detectionTime: "Detection Time",
    whyClassified: "Why Classified",
    similarityScore: "Similarity Score",
    dielectricEstimate: "Dielectric Est.",
    frequencyResponse: "Frequency Response",
    threeDSubsurface: "3D Subsurface Visualization",
    soilLayers: "Soil Layers",
    undergroundObjects: "Underground Objects",
    voids: "Voids / Cavities",
    utilities: "Utility Lines",
    geologicalStructures: "Geological Structures",
    rotate: "Rotate",
    pan: "Pan",
    zoom: "Zoom",
    layerToggle: "Layer Toggle",
    transparency: "Transparency Control",
    sectionCut: "Section Cut",
    volumeRender: "Volume Rendering",
    smartAlerts: "Smart Alert System",
    materialAnalysisTitle: "Material Analysis Mode",
    materialPrediction: "Material Prediction",
    frequencySignature: "Frequency Signature",
    reflectionSignature: "Reflection Signature",
    similarObjects: "Similar Objects",
    freqCurves: "Frequency Response Curves",
    reflectionGraphs: "Reflection Intensity Graphs",
    similarityCharts: "Material Similarity Chart",
    aiExplanation: "AI Analysis Details",
    logsTitle: "Logs and Locations",
    gpsLoc: "GPS Location",
    operator: "Operator",
    duration: "Scan Duration",
    results: "Detection Results",
    listView: "List View",
    timelineView: "Timeline View",
    mapView: "Map View",
    exportPdf: "Export PDF Report",
    exportCsv: "Export CSV Data",
    exportPng: "Export PNG Chart",
    aiCopilotTitle: "AI Copilot Assistant",
    settingsFreq: "Frequency Config",
    settingsPulse: "Pulse Config",
    settingsGain: "Gain Control",
    settingsNoise: "Noise Filtering",
    settingsAntenna: "Antenna Parameters",
    settingsRes: "Scan Resolution",
    settingsLang: "Language",
    settingsTheme: "Theme Selection",
    settingsGps: "GPS Settings",
    settingsStorage: "Storage Settings",
    targetDetected: "Target Detected!",
    gold: "Gold",
    silver: "Silver",
    copper: "Copper",
    iron: "Iron",
    aluminum: "Aluminum",
    pipe: "Pipe / Conduit",
    cable: "Cable / Utility",
    concrete: "Concrete Block",
    water: "Water / Wet Soil",
    rock: "Bedrock / Stone",
    plastic: "Plastic Object",
    void: "Void / Cavity",
    tunnel: "Tunnel / Passage",
    buriedObj: "Buried Object",
    unknownObj: "Unknown Object",
    metal: "Metal Anomaly",
    steel: "Steel Rebar",
    soil: "Soil Stratum",
    emptyVoid: "Air Void"
  },
  de: {
    title: "AntiGravity AI GPR-Suite",
    subtitle: "Industrielles KI-gestütztes Bodenradar",
    diagnosticsTitle: "Hardware-Diagnosesystem",
    diagnosticsSub: "System wird gestartet und Hardwaretests werden durchgeführt...",
    diagnosticsCheck: "Überprüfung...",
    runDiagnostics: "Selbsttest wiederholen",
    card1Title: "LIVE-GPR-SCAN",
    card1Desc: "Echtzeit-Bodenabtastung und KI-Analysemodus",
    card2Title: "MATERIALANALYSE",
    card2Desc: "Materialtyp-Vorhersage über Frequenzgang und Spektrum",
    card3Title: "PROTOKOLLE UND ORTE",
    card3Desc: "Vergangene Scan-Daten, GPS-Routen und Berichtsexport",
    settingsTitle: "EINSTELLUNGEN",
    settingsDesc: "Hardwareparameter, Signalfilterung und Einstellungen",
    batterySystem: "Batteriesystem",
    pulse10v: "Puls 10V Generator",
    pulse33v: "Puls 3.3V Generator",
    regulator33to5: "3.3V → 5V Regler",
    boostConverter: "Aufwärtswandler",
    transmitterSystem: "Sendersystem",
    receiverSystem: "Empfängersystem",
    gpsConnection: "GPS-Verbindung",
    aiEngine: "KI-Analyse-Engine",
    storageSystem: "Speicher- und Protokollsystem",
    statusReady: "Bereit",
    statusWarning: "Warnung",
    statusFault: "Störung",
    startScan: "Scan starten",
    stopScan: "Scan stoppen",
    pauseScan: "Pause",
    scanProgress: "Scan-Fortschritt",
    signalQuality: "Signalqualität",
    scanStatus: "Boden-Scan-Status",
    aiAlerts: "KI-Erkennungswarnungen",
    radargram: "Echtzeit-Radargramm",
    liveSignalStream: "Live-Signalstrom",
    signalStrength: "Signalstärke",
    penetrationDepth: "Eindringtiefe",
    targetMarkers: "Zielmarkierungen",
    reflectionVisual: "Reflexionsvisualisierung",
    scanCoverageMap: "Scan-Abdeckungskarte",
    transmitterPanel: "Sender-Überwachungspanel",
    pulseWaveform: "Puls-Wellenform",
    peakVoltage: "Spitzenspannung",
    pulseWidth: "Pulsbreite",
    pulseFreq: "Pulsfrequenz",
    repRate: "Wiederholrate",
    amplitude: "Amplitude",
    fftSpectrum: "FFT-Spektrumanalyse",
    powerPanel: "Leistungs-Überwachungspanel",
    batteryPercentage: "Batterieladung",
    batteryVoltage: "Batteriespannung",
    operatingTime: "Kalan Betriebszeit",
    currentConsumption: "Stromverbrauch",
    temperature: "Temperatur",
    receiverPanel: "Empfänger-Analysepanel",
    reflectionDelay: "Reflexionsverzögerung",
    reflectionStrength: "Reflexionsstärke",
    attenuation: "Signaldämpfung",
    materialConfidence: "Material-Konfidenz",
    aiDetectionTitle: "KI-Objekterkennung",
    objectType: "Objekttyp",
    confidenceScore: "Konfidenzwert",
    estimatedDepth: "Geschätzte Tiefe",
    estimatedDim: "Geschätzte Maße",
    detectionTime: "Erkennungszeit",
    whyClassified: "Klassifizierungsgrund",
    similarityScore: "Ähnlichkeitswert",
    dielectricEstimate: "Dielektrizitätswert",
    frequencyResponse: "Frequenzgang",
    threeDSubsurface: "3D-Untergrund-Visualisierung",
    soilLayers: "Bodenschichten",
    undergroundObjects: "Unterirdische Objekte",
    voids: "Hohlräume / Hohlraum",
    utilities: "Versorgungsleitungen",
    geologicalStructures: "Geologische Strukturen",
    rotate: "Drehen",
    pan: "Verschieben",
    zoom: "Zoomen",
    layerToggle: "Ebene umschalten",
    transparency: "Transparenzregler",
    sectionCut: "Schnittansicht",
    volumeRender: "Volumen-Rendering",
    smartAlerts: "Intelligentes Warnsystem",
    materialAnalysisTitle: "Materialanalyse-Modus",
    materialPrediction: "Materialvorhersage",
    frequencySignature: "Frequenz-Signatur",
    reflectionSignature: "Reflexions-Signatur",
    similarObjects: "Ähnliche Objekte",
    freqCurves: "Frequenzgangkurven",
    reflectionGraphs: "Reflexionsintensität",
    similarityCharts: "Materialähnlichkeitstabelle",
    aiExplanation: "KI-Analyseerklärung",
    logsTitle: "Protokolle und Orte",
    gpsLoc: "GPS-Position",
    operator: "Bediener",
    duration: "Scandauer",
    results: "Ergebnisse",
    listView: "Listenansicht",
    timelineView: "Zeitleiste",
    mapView: "Kartenansicht",
    exportPdf: "PDF-Bericht exportieren",
    exportCsv: "Als CSV speichern",
    exportPng: "PNG-Grafik exportieren",
    aiCopilotTitle: "KI-Copilot-Assistent",
    settingsFreq: "Frequenz-Konfig",
    settingsPulse: "Puls-Konfig",
    settingsGain: "Verstärkungsregelung",
    settingsNoise: "Rauschfilterung",
    settingsAntenna: "Antennenparameter",
    settingsRes: "Scanauflösung",
    settingsLang: "Sprachauswahl",
    settingsTheme: "Themenauswahl",
    settingsGps: "GPS-Einstellungen",
    settingsStorage: "Speicher-Einstellungen",
    targetDetected: "Ziel erkannt!",
    gold: "Gold",
    silver: "Silber",
    copper: "Kupfer",
    iron: "Eisen",
    aluminum: "Aluminium",
    pipe: "Rohrleitung",
    cable: "Kabel / Leitung",
    concrete: "Betonblock",
    water: "Wasser / Nässe",
    rock: "Felsgestein",
    plastic: "Kunststoffobjekt",
    void: "Hohlraum",
    tunnel: "Tunnel / Gang",
    buriedObj: "Begrabenes Objekt",
    unknownObj: "Unbekanntes Objekt",
    metal: "Metallanomalie",
    steel: "Stahlträger",
    soil: "Bodenschicht",
    emptyVoid: "Lufthohlraum"
  },
  fr: {
    title: "AntiGravity AI GPR Suite",
    subtitle: "Radar de sol industriel assisté par IA",
    diagnosticsTitle: "Système de Diagnostic Matériel",
    diagnosticsSub: "Initialisation du système et exécution des tests...",
    diagnosticsCheck: "Vérification...",
    runDiagnostics: "Relancer l'autotest",
    card1Title: "SCAN GPR EN DIRECT",
    card1Desc: "Mode de balayage du sol en temps réel et analyse IA",
    card2Title: "ANALYSE DE MATIÈRE",
    card2Desc: "Prédiction du matériau via réponse fréquentielle et spectre",
    card3Title: "REGISTRES ET LOCATIONS",
    card3Desc: "Données de scan passées, tracés GPS et export de rapports",
    settingsTitle: "PARAMÈTRES",
    settingsDesc: "Paramètres matériels, filtrage du signal et préférences",
    batterySystem: "Système de Batterie",
    pulse10v: "Générateur d'impulsions 10V",
    pulse33v: "Générateur d'impulsions 3.3V",
    regulator33to5: "Régulateur 3.3V → 5V",
    boostConverter: "Convertisseur Boost",
    transmitterSystem: "Système Transmetteur",
    receiverSystem: "Système Récepteur",
    gpsConnection: "Connexion GPS",
    aiEngine: "Moteur d'Analyse IA",
    storageSystem: "Système de Stockage",
    statusReady: "Prêt",
    statusWarning: "Avertissement",
    statusFault: "Défaut",
    startScan: "Lancer le scan",
    stopScan: "Arrêter le scan",
    pauseScan: "Pause",
    scanProgress: "Progression du scan",
    signalQuality: "Qualité du signal",
    scanStatus: "Statut du scan",
    aiAlerts: "Alertes de Détection IA",
    radargram: "Radargramme en temps réel",
    liveSignalStream: "Flux de signal en direct",
    signalStrength: "Force du signal",
    penetrationDepth: "Profondeur de pénétration",
    targetMarkers: "Marqueurs de cible",
    reflectionVisual: "Visualisation des réflexions",
    scanCoverageMap: "Carte de couverture",
    transmitterPanel: "Panneau de Surveillance Émetteur",
    pulseWaveform: "Forme d'onde d'impulsion",
    peakVoltage: "Tension de crête",
    pulseWidth: "Largeur d'impulsion",
    pulseFreq: "Fréquence d'impulsion",
    repRate: "Taux de répétition",
    amplitude: "Amplitude",
    fftSpectrum: "Analyse spectrale FFT",
    powerPanel: "Panneau de Puissance",
    batteryPercentage: "Pourcentage Batterie",
    batteryVoltage: "Tension Batterie",
    operatingTime: "Temps d'opération restant",
    currentConsumption: "Consommation de courant",
    temperature: "Température",
    receiverPanel: "Panneau d'Analyse Récepteur",
    reflectionDelay: "Délai de réflexion",
    reflectionStrength: "Force de réflexion",
    attenuation: "Atténuation du signal",
    materialConfidence: "Confiance matériau",
    aiDetectionTitle: "Détection d'objets par IA",
    objectType: "Type d'objet",
    confidenceScore: "Score de confiance",
    estimatedDepth: "Profondeur estimée",
    estimatedDim: "Dimensions estimées",
    detectionTime: "Heure de détection",
    whyClassified: "Raison de classification",
    similarityScore: "Score de similarité",
    dielectricEstimate: "Estimation diélectrique",
    frequencyResponse: "Réponse fréquentielle",
    threeDSubsurface: "Visualisation 3D sous-sol",
    soilLayers: "Couches de sol",
    undergroundObjects: "Objets souterrains",
    voids: "Cavités / Vides",
    utilities: "Réseaux / Canalisations",
    geologicalStructures: "Structures géologiques",
    rotate: "Pivoter",
    pan: "Glisser",
    zoom: "Zoomer",
    layerToggle: "Activer les couches",
    transparency: "Contrôle de transparence",
    sectionCut: "Coupe transversale",
    volumeRender: "Rendu volumétrique",
    smartAlerts: "Système d'Alerte Intelligent",
    materialAnalysisTitle: "Mode d'Analyse de Matière",
    materialPrediction: "Prédiction de matériau",
    frequencySignature: "Signature fréquentielle",
    reflectionSignature: "Signature de réflexion",
    similarObjects: "Objets similaires",
    freqCurves: "Courbes de réponse",
    reflectionGraphs: "Graphiques d'intensité",
    similarityCharts: "Tableau de similarité",
    aiExplanation: "Explication de l'IA",
    logsTitle: "Registres et positions",
    gpsLoc: "Position GPS",
    operator: "Opérateur",
    duration: "Durée du scan",
    results: "Résultats",
    listView: "Vue liste",
    timelineView: "Vue chronologique",
    mapView: "Vue carte",
    exportPdf: "Exporter rapport PDF",
    exportCsv: "Enregistrer sous CSV",
    exportPng: "Exporter graphique PNG",
    aiCopilotTitle: "Copilote IA Dédié",
    settingsFreq: "Configuration Fréquence",
    settingsPulse: "Configuration Impulsion",
    settingsGain: "Contrôle du Gain",
    settingsNoise: "Filtrage du Bruit",
    settingsAntenna: "Paramètres Antenne",
    settingsRes: "Résolution du scan",
    settingsLang: "Sélection de la langue",
    settingsTheme: "Choix du thème",
    settingsGps: "Paramètres GPS",
    settingsStorage: "Stockage des données",
    targetDetected: "Cible détectée !",
    gold: "Or",
    silver: "Argent",
    copper: "Cuivre",
    iron: "Fer",
    aluminum: "Aluminium",
    pipe: "Tuyau / Canalisation",
    cable: "Câble / Réseau",
    concrete: "Massif béton",
    water: "Eau / Sol humide",
    rock: "Roche / Pierre",
    plastic: "Objet plastique",
    void: "Cavité",
    tunnel: "Tunnel / Galerie",
    buriedObj: "Objet enfoui",
    unknownObj: "Objet inconnu",
    metal: "Anomalie métallique",
    steel: "Poutrelle acier",
    soil: "Couche de terre",
    emptyVoid: "Poche d'air"
  },
  ru: {
    title: "AntiGravity AI GPR Suite",
    subtitle: "Промышленный ИИ-радар подповерхностного зондирования",
    diagnosticsTitle: "Система диагностики оборудования",
    diagnosticsSub: "Запуск системы и проверка аппаратных модулей...",
    diagnosticsCheck: "Проверка...",
    runDiagnostics: "Повторить тест",
    card1Title: "ЖИВОЕ GPR-СКАНИРОВАНИЕ",
    card1Desc: "Режим реального времени и ИИ-анализ грунтовых слоев",
    card2Title: "АНАЛИЗ МАТЕРИАЛОВ",
    card2Desc: "Определение типа материала по спектру и частотному отклику",
    card3Title: "ЖУРНАЛЫ И КООРДИНАТЫ",
    card3Desc: "История сканирования, GPS-маршруты и экспорт отчетов",
    settingsTitle: "НАСТРОЙКИ",
    settingsDesc: "Параметры сигналов, фильтрация шумов и интерфейс",
    batterySystem: "Система батареи",
    pulse10v: "Генератор импульсов 10 В",
    pulse33v: "Генератор импульсов 3.3 В",
    regulator33to5: "Регулятор 3.3 В → 5 В",
    boostConverter: "Повышающий преобразователь",
    transmitterSystem: "Система передатчика",
    receiverSystem: "Система приемника",
    gpsConnection: "GPS-соединение",
    aiEngine: "ИИ-анализатор",
    storageSystem: "Система хранения данных",
    statusReady: "Готов",
    statusWarning: "Предупр.",
    statusFault: "Ошибка",
    startScan: "Начать сканирование",
    stopScan: "Остановить",
    pauseScan: "Пауза",
    scanProgress: "Прогресс сканирования",
    signalQuality: "Качество сигнала",
    scanStatus: "Статус сканирования",
    aiAlerts: "ИИ-предупреждения",
    radargram: "Радарграмма в реальном времени",
    liveSignalStream: "Живой сигнал",
    signalStrength: "Мощность сигнала",
    penetrationDepth: "Глубина зондирования",
    targetMarkers: "Маркеры целей",
    reflectionVisual: "Визуализация отражений",
    scanCoverageMap: "Карта покрытия сканирования",
    transmitterPanel: "Панель передатчика",
    pulseWaveform: "Форма импульса",
    peakVoltage: "Пиковое напряжение",
    pulseWidth: "Ширина импульса",
    pulseFreq: "Частота импульсов",
    repRate: "Частота повторения",
    amplitude: "Амплитуда",
    fftSpectrum: "БПФ-спектрограмма",
    powerPanel: "Панель питания",
    batteryPercentage: "Заряд батареи",
    batteryVoltage: "Напряжение батареи",
    operatingTime: "Оставшееся время работы",
    currentConsumption: "Потребление тока",
    temperature: "Температура",
    receiverPanel: "Панель приемника",
    reflectionDelay: "Задержка отражения",
    reflectionStrength: "Сила отражения",
    attenuation: "Затухание сигнала",
    materialConfidence: "Достоверность материала",
    aiDetectionTitle: "ИИ-обнаружение объектов",
    objectType: "Тип объекта",
    confidenceScore: "Достоверность",
    estimatedDepth: "Оценка глубины",
    estimatedDim: "Оценка размеров",
    detectionTime: "Время обнаружения",
    whyClassified: "Причина классификации",
    similarityScore: "Индекс сходства",
    dielectricEstimate: "Диэлектр. проницаемость",
    frequencyResponse: "Частотный отклик",
    threeDSubsurface: "3D-визуализация грунта",
    soilLayers: "Слои почвы",
    undergroundObjects: "Подземные объекты",
    voids: "Пустоты / Полости",
    utilities: "Коммуникации / Трубы",
    geologicalStructures: "Геологические структуры",
    rotate: "Вращать",
    pan: "Панорама",
    zoom: "Масштаб",
    layerToggle: "Переключить слои",
    transparency: "Управление прозрачностью",
    sectionCut: "Поперечный разрез",
    volumeRender: "Объемный рендеринг",
    smartAlerts: "Умные предупреждения",
    materialAnalysisTitle: "Режим анализа материалов",
    materialPrediction: "Прогноз материала",
    frequencySignature: "Частотная сигнатура",
    reflectionSignature: "Сигнатура отражения",
    similarObjects: "Похожие объекты",
    freqCurves: "Кривые частотного отклика",
    reflectionGraphs: "График интенсивности отражения",
    similarityCharts: "Диаграмма сходства материалов",
    aiExplanation: "Пояснение искусственного интеллекта",
    logsTitle: "Журнал и локации",
    gpsLoc: "Координаты GPS",
    operator: "Оператор",
    duration: "Длительность сканирования",
    results: "Найденные объекты",
    listView: "Список",
    timelineView: "Хронология",
    mapView: "Карта",
    exportPdf: "Экспорт отчета PDF",
    exportCsv: "Экспорт данных CSV",
    exportPng: "Экспорт графика PNG",
    aiCopilotTitle: "ИИ-ассистент Copilot",
    settingsFreq: "Настройка частоты",
    settingsPulse: "Настройка импульса",
    settingsGain: "Регулировка усиления (Gain)",
    settingsNoise: "Шумоподавление",
    settingsAntenna: "Параметры антенны",
    settingsRes: "Разрешение сканирования",
    settingsLang: "Выбор языка",
    settingsTheme: "Выбор темы",
    settingsGps: "Параметры GPS",
    settingsStorage: "Настройки накопителя",
    targetDetected: "Цель обнаружена!",
    gold: "Золото",
    silver: "Серебро",
    copper: "Медь",
    iron: "Железо",
    aluminum: "Алюминий",
    pipe: "Труба / Магистраль",
    cable: "Кабель / Провод",
    concrete: "Бетонная плита",
    water: "Вода / Влажная почва",
    rock: "Скала / Камень",
    plastic: "Пластиковый объект",
    void: "Пустота / Полость",
    tunnel: "Туннель / Проход",
    buriedObj: "Захороненный объект",
    unknownObj: "Неизвестный объект",
    metal: "Металлическая аномалия",
    steel: "Стальной профиль",
    soil: "Слой грунта",
    emptyVoid: "Воздушный карман"
  },
  ar: {
    title: "AntiGravity AI GPR Suite",
    subtitle: "رادار أرضي صناعي مدعوم بالذكاء الاصطناعي",
    diagnosticsTitle: "نظام تشخيص الأجهزة",
    diagnosticsSub: "تهيئة النظام وإجراء اختبارات الأجهزة...",
    diagnosticsCheck: "جاري الفحص...",
    runDiagnostics: "إعادة الاختبار الذاتي",
    card1Title: "مسح راداري مباشر",
    card1Desc: "وضع مسح الأرض في الوقت الفعلي وتحليل الذكاء الاصطناعي",
    card2Title: "تحليل المواد",
    card2Desc: "التنبؤ بنوع المادة عبر استجابة التردد والطيف",
    card3Title: "السجلات والمواقع",
    card3Desc: "بيانات المسح السابقة ومسارات نظام تحديد المواقع وتصدير التقارير",
    settingsTitle: "الإعدادات",
    settingsDesc: "معلمات الأجهزة وتصفية الإشارات والتفضيلات العامة",
    batterySystem: "نظام البطارية",
    pulse10v: "مولد نبضات 10 فولت",
    pulse33v: "مولد نبضات 3.3 فولت",
    regulator33to5: "منظم جهد 3.3 فولت ← 5 فولت",
    boostConverter: "محول رفع الجهد",
    transmitterSystem: "نظام الإرسال",
    receiverSystem: "نظام الاستقبال",
    gpsConnection: "اتصال GPS",
    aiEngine: "محرك تحليل الذكاء الاصطناعي",
    storageSystem: "نظام التخزين والتسجيل",
    statusReady: "جاهز",
    statusWarning: "تحذير",
    statusFault: "عطل",
    startScan: "بدء المسح",
    stopScan: "إيقاف المسح",
    pauseScan: "إيقاف مؤقت",
    scanProgress: "تقدم المسح",
    signalQuality: "جودة الإشارة",
    scanStatus: "حالة مسح الأرض",
    aiAlerts: "تنبيهات الكشف بالذكاء الاصطناعي",
    radargram: "مخطط الرادار في الوقت الفعلي",
    liveSignalStream: "تدفق الإشارة المباشر",
    signalStrength: "قوة الإشارة",
    penetrationDepth: "عمق الاختراق",
    targetMarkers: "مؤشرات الهدف",
    reflectionVisual: "تصوير الانعكاس",
    scanCoverageMap: "خريطة تغطية المسح",
    transmitterPanel: "لوحة مراقبة جهاز الإرسال",
    pulseWaveform: "شكل موجة النبض",
    peakVoltage: "جهد الذروة",
    pulseWidth: "عرض النبضة",
    pulseFreq: "تردد النبض",
    repRate: "معدل التكرار",
    amplitude: "السعة",
    fftSpectrum: "تحليل طيف FFT",
    powerPanel: "لوحة مراقبة الطاقة",
    batteryPercentage: "نسبة البطارية",
    batteryVoltage: "جهد البطارية",
    operatingTime: "وقت التشغيل المتبقي",
    currentConsumption: "استهلاك التيار",
    temperature: "درجة الحرارة",
    receiverPanel: "لوحة تحليل جهاز الاستقبال",
    reflectionDelay: "تأخير الانعكاس",
    reflectionStrength: "قوة الانعكاس",
    attenuation: "توهين الإشارة",
    materialConfidence: "درجة موثوقية المادة",
    aiDetectionTitle: "كشف الكائنات بالذكاء الاصطناعي",
    objectType: "نوع الجسم",
    confidenceScore: "درجة الثقة",
    estimatedDepth: "العمق المقدر",
    estimatedDim: "الأبعاد المقدرة",
    detectionTime: "وقت الكشف",
    whyClassified: "سبب التصنيف",
    similarityScore: "درجة التشابه",
    dielectricEstimate: "تقدير العزل الكهربائي",
    frequencyResponse: "استجابة التردد",
    threeDSubsurface: "تصوير ثلاثي الأبعاد لباطن الأرض",
    soilLayers: "طبقات التربة",
    undergroundObjects: "الأجسام الجوفية",
    voids: "الفجوات / التجاويف",
    utilities: "خطوط المرافق والخدمات",
    geologicalStructures: "الهياكل الجيولوجية",
    rotate: "تدوير",
    pan: "تحريك",
    zoom: "تكبير/تصغير",
    layerToggle: "تبديل الطبقات",
    transparency: "التحكم في الشفافية",
    sectionCut: "أخذ مقطع",
    volumeRender: "رسم حجمي",
    smartAlerts: "نظام التنبيه الذكي",
    materialAnalysisTitle: "وضع تحليل المواد",
    materialPrediction: "التنبؤ بالمادة",
    frequencySignature: "توقيع التردد",
    reflectionSignature: "توقيع الانعكاس",
    similarObjects: "الأجسام المشابهة",
    freqCurves: "منحنيات استجابة التردد",
    reflectionGraphs: "رسومات كثافة الانعكاس",
    similarityCharts: "مخطط تشابه المواد",
    aiExplanation: "توضيح الذكاء الاصطناعي",
    logsTitle: "السجلات والمواقع",
    gpsLoc: "موقع GPS",
    operator: "المشغل",
    duration: "مدة المسح",
    results: "نتائج الكشف",
    listView: "عرض القائمة",
    timelineView: "الخط الزمني",
    mapView: "عرض الخريطة",
    exportPdf: "تصدير تقرير PDF",
    exportCsv: "حفظ كـ CSV",
    exportPng: "تصدير رسم PNG",
    aiCopilotTitle: "مساعد الذكاء الاصطناعي (Copilot)",
    settingsFreq: "تكوين التردد",
    settingsPulse: "تكوين النبض",
    settingsGain: "التحكم في الكسب (Gain)",
    settingsNoise: "تصفية الضوضاء",
    settingsAntenna: "معلمات الهوائي",
    settingsRes: "دقة المسح",
    settingsLang: "اختيار اللغة",
    settingsTheme: "تحديد المظهر",
    settingsGps: "إعدادات GPS",
    settingsStorage: "إعدادات تخزين البيانات",
    targetDetected: "تم اكتشاف هدف!",
    gold: "ذهب",
    silver: "فضة",
    copper: "نحاس",
    iron: "حديد",
    aluminum: "ألومنيوم",
    pipe: "أنبوب / ماسورة",
    cable: "كابل / كهرباء",
    concrete: "كتلة خرسانية",
    water: "مياه / تربة رطبة",
    rock: "صخرة / حجر",
    plastic: "جسم بلاستيكي",
    void: "فجوة / تجويف",
    tunnel: "نفق / ممر",
    buriedObj: "جسم مدفون",
    unknownObj: "جسم غير معروف",
    metal: "شذوذ معدني",
    steel: "جسر فولاذي",
    soil: "طبقة ترابية",
    emptyVoid: "جيب هوائي"
  }
};

const LanguageContext = createContext<{
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}>({
  language: 'tr',
  setLanguage: () => {},
  t: translationsMap.tr,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('tr');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = translationsMap[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
